#!/bin/bash
set -e

APP="$1"
PORT="$2"
APP_ROOT="/home/git"

update_nodes() {
  vars=`echo -e "$1"`

  for word in $vars; do
    KEY=`echo $word | cut -d"=" -f1`
    VALUE=`echo $word | cut -d"=" -f2-`
    domains=`echo $VALUE | tr ',' '\n'`
    for domain in $domains; do
      echo $KEY=$domain
      # will run as dokku command due to /home/git/.sshcommand
      # hardcoded to 6 processes for now; could put this in configuration or read from file
      PROCESSES=6
      echo "ssh git@$domain nodes:internal:deploy $APP $PORT $KEY $PROCESSES"
      echo -e `ssh git@$domain nodes:internal:deploy $APP $PORT $KEY $PROCESSES`
    done
  done
}

if [[ -f "$APP_ROOT/$APP/NODES" ]]; then
  echo "Running NODES post-deploy..."
  REMOTE_APP="localhost:5000/appl/$APP"
  echo "$REMOTE_APP $APP"
  docker tag app/$APP $REMOTE_APP
  docker push $REMOTE_APP
  update_nodes `cat $APP_ROOT/$APP/NODES`
  echo "Finished running NODES post-deploy."
else
  echo "Skipping NODES post-deploy, no nodes present."
fi
